# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main  # deploy when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SERVER_USER: ubuntu          # or ec2-user
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "
            cd /home/ubuntu/express-cicd-server &&
            git pull &&
            npm install &&
            pm2 restart all
          "
